"""GitHub issue creation and manipulation."""

import attr

from githubcap.base import GitHubBase

from .license import License
from .user import User


@attr.s
class Repository(GitHubBase):
    archive_url = attr.ib(type=str),
    archived = attr.ib(type=bool)
    assignees_url = attr.ib(type=str)
    blobs_url = attr.ib(type=str)
    branches_url = attr.ib(type=str)
    clone_url = attr.ib(type=str)
    collaborators_url = attr.ib(type=str)
    comments_url = attr.ib(type=str)
    commits_url = attr.ib(type=str)
    compare_url = attr.ib(type=str)
    contents_url = attr.ib(type=str)
    contributors_url = attr.ib(type=str)
    created_at = attr.ib(type=str)
    default_branch = attr.ib(type=str)
    deployments_url = attr.ib(type=str)
    description = attr.ib(type=str)
    downloads_url = attr.ib(type=str)
    events_url = attr.ib(type=str)
    fork = attr.ib(type=bool)
    forks = attr.ib(type=int)
    forks_count = attr.ib(type=int)
    forks_url = attr.ib(type=str)
    full_name = attr.ib(type=str)
    git_commits_url = attr.ib(type=str)
    git_refs_url = attr.ib(type=str)
    git_tags_url = attr.ib(type=str)
    git_url = attr.ib(type=str)
    has_downloads = attr.ib(type=bool)
    has_issues = attr.ib(type=bool)
    has_pages = attr.ib(type=bool)
    has_projects = attr.ib(type=bool)
    has_wiki = attr.ib(type=bool)
    homepage = attr.ib(type=str)
    hooks_url = attr.ib(type=str)
    html_url = attr.ib(type=str)
    id = attr.ib(type=int)
    issue_comment_url = attr.ib(type=str)
    issue_events_url = attr.ib(type=str)
    issues_url = attr.ib(type=str)
    keys_url = attr.ib(type=str)
    labels_url = attr.ib(type=str)
    language = attr.ib(type=str)
    languages_url = attr.ib(type=str)
    license = attr.ib(type=License)
    merges_url = attr.ib(type=str)
    milestones_url = attr.ib(type=str)
    mirror_url = attr.ib(type=str)
    name = attr.ib(type=str)
    notifications_url = attr.ib(type=str)
    open_issues = attr.ib(type=int)
    open_issues_count = attr.ib(type=int)
    owner = attr.ib(type=User)
    private = attr.ib(type=bool)
    pulls_url = attr.ib(type=str)
    pushed_at = attr.ib(type=str)
    releases_url = attr.ib(type=str)
    size = attr.ib(type=int)
    ssh_url = attr.ib(type=str)
    stargazers_count = attr.ib(type=int)
    stargazers_url = attr.ib(type=str)
    statuses_url = attr.ib(type=str)
    subscribers_url = attr.ib(type=str)
    subscription_url = attr.ib(type=str)
    svn_url = attr.ib(type=str)
    tags_url = attr.ib(type=str)
    teams_url = attr.ib(type=str)
    trees_url = attr.ib(type=str)
    updated_at = attr.ib(type=str)
    url = attr.ib(type=str)
    watchers = attr.ib(type=int)
    watchers_count = attr.ib(type=int)
