"""GitHub repository schema."""

from voluptuous import Any
from voluptuous import Url

from .license import LICENSE_SCHEMA
from .user import USER_SCHEMA

# pylint: disable=no-value-for-parameter


REPOSITORY_SCHEMA = {
    "archive_url": Url(),
    "archived": bool,
    "assignees_url": Url(),
    "blobs_url": Url(),
    "branches_url": Url(),
    "clone_url": Url(),
    "collaborators_url": Url(),
    "comments_url": Url(),
    "commits_url": Url(),
    "compare_url": Url(),
    "contents_url": Url(),
    "contributors_url": Url(),
    "created_at": str,
    "default_branch": str,
    "deployments_url": Url(),
    "description": Any(str, None),
    "downloads_url": Url(),
    "events_url": Url(),
    "fork": bool,
    "forks": int,
    "forks_count": int,
    "forks_url": Url(),
    "full_name": str,
    "git_commits_url": Url(),
    "git_refs_url": Url(),
    "git_tags_url": Url(),
    "git_url": Url(),
    "has_downloads": bool,
    "has_issues": bool,
    "has_pages": bool,
    "has_projects": bool,
    "has_wiki": bool,
    "homepage": Any(str, Url(), None),
    "hooks_url": Url(),
    "html_url": Url(),
    "id": int,
    "issue_comment_url": Url(),
    "issue_events_url": Url(),
    "issues_url": Url(),
    "keys_url": Url(),
    "labels_url": Url(),
    "language": Any(None, str),
    "languages_url": Url(),
    "license": Any(None, LICENSE_SCHEMA),
    "merges_url": Url(),
    "milestones_url": Url(),
    "mirror_url": None,
    "name": str,
    "notifications_url": Url(),
    "open_issues": int,
    "open_issues_count": int,
    "owner": USER_SCHEMA,
    "private": bool,
    "pulls_url": Url(),
    "pushed_at": str,
    "releases_url": Url(),
    "size": int,
    "ssh_url": str,
    "stargazers_count": int,
    "stargazers_url": Url(),
    "statuses_url": Url(),
    "subscribers_url": Url(),
    "subscription_url": Url(),
    "svn_url": Url(),
    "tags_url": Url(),
    "teams_url": Url(),
    "trees_url": Url(),
    "updated_at": str,
    "url": Url(),
    "watchers": int,
    "watchers_count": int
}
